// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MovieAutocompleteController from "./movie_autocomplete_controller"
application.register("movie-autocomplete", MovieAutocompleteController)

import ShowOverviewController from "./show_overview_controller"
application.register("show-overview", ShowOverviewController)
